server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  profiles:
    active: native
  application:
    name: ruigou-config-server
  cloud:
    config:
      server:
        native:
          search-locations: F:/Github/application_config
#        git:
#          uri: https://github.com/GHforRL/application_config.git
#          username: GHforRL
#          password: rui9527.cn